// import type { Metadata } from "next";

// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"

//     >

//       <body>{children}</body>
//     </html>
//   );
// }
import { Header } from "@/components/header";
import { SanityLive } from "@/sanity/lib/live";

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="bg-white min-h-screen">
          <Header />
          {children}
          <SanityLive />
        </section>
      </body>
    </html>
  );
}
